import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "../fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={poppins.style} className={`dark antialiased`}>
        {children}
      </body>
    </html>
  );
}
